/**
 * Comprehensive drug interaction seed data.
 * Covers WHO Essential Medicines + commonly prescribed drugs in Africa.
 * Sources: BNF, Lexicomp, Stockley's, WHO Model Formulary.
 */

export interface SeedInteraction {
  drug1: string
  drug2: string
  severity: 'contraindicated' | 'critical' | 'severe' | 'moderate' | 'mild'
  category: 'drug-drug' | 'drug-disease' | 'drug-allergy' | 'duplicate-therapy' | 'drug-food'
  description: string
  mechanism: string
  management: string
  onset: string
  evidence: string
  source: string
}

export function seedInteractions(): SeedInteraction[] {
  return [
    // ════════════════════════════════════════════════════════════════════
    // CONTRAINDICATED (absolute — do not combine)
    // ════════════════════════════════════════════════════════════════════
    {
      drug1: 'metformin', drug2: 'contrast media',
      severity: 'contraindicated', category: 'drug-drug',
      description: 'Risk of lactic acidosis with iodinated contrast media',
      mechanism: 'Contrast-induced acute kidney injury impairs metformin excretion, leading to lactic acid accumulation',
      management: 'Stop metformin 48h before contrast study; hold for 48h after; resume only if renal function is normal',
      onset: 'delayed', evidence: 'established', source: 'BNF, MHRA',
    },
    {
      drug1: 'clopidogrel', drug2: 'omeprazole',
      severity: 'contraindicated', category: 'drug-drug',
      description: 'Omeprazole irreversibly inhibits CYP2C19, reducing clopidogrel activation',
      mechanism: 'Clopidogrel is a prodrug requiring CYP2C19 for activation; omeprazole is a potent CYP2C19 inhibitor',
      management: 'Use pantoprazole instead (minimal CYP2C19 inhibition). Avoid esomeprazole as well',
      onset: 'delayed', evidence: 'established', source: 'FDA, ESC Guidelines',
    },
    {
      drug1: 'methotrexate', drug2: 'trimethoprim',
      severity: 'contraindicated', category: 'drug-drug',
      description: 'Both are folate antagonists — risk of severe, potentially fatal bone marrow suppression',
      mechanism: 'Additive antifolate activity leading to megaloblastic anaemia and pancytopenia',
      management: 'Avoid combination entirely. Use alternative antibiotics',
      onset: 'delayed', evidence: 'established', source: 'BNF, Stockley\'s',
    },
    {
      drug1: 'methotrexate', drug2: 'co-trimoxazole',
      severity: 'contraindicated', category: 'drug-drug',
      description: 'Both are folate antagonists — risk of severe bone marrow suppression',
      mechanism: 'Additive antifolate activity; trimethoprim component has same mechanism as methotrexate',
      management: 'Avoid combination entirely',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'alcohol', drug2: 'metronidazole',
      severity: 'contraindicated', category: 'drug-food',
      description: 'Disulfiram-like reaction: severe nausea, vomiting, flushing, tachycardia, hypotension',
      mechanism: 'Metronidazole inhibits aldehyde dehydrogenase, causing acetaldehyde accumulation',
      management: 'Advise patient: no alcohol during treatment and for 72 hours after stopping metronidazole',
      onset: 'immediate', evidence: 'established', source: 'BNF, WHO Model Formulary',
    },
    {
      drug1: 'alcohol', drug2: 'disulfiram',
      severity: 'contraindicated', category: 'drug-food',
      description: 'Severe disulfiram-alcohol reaction: flushing, nausea, palpitations, potentially fatal',
      mechanism: 'Disulfiram inhibits aldehyde dehydrogenase; acetaldehyde accumulates to toxic levels',
      management: 'Patients on disulfiram must avoid all alcohol-containing products including mouthwash and some sauces',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'warfarin', drug2: 'mifepristone',
      severity: 'contraindicated', category: 'drug-drug',
      description: 'Mifepristone is a potent CYP3A4 inducer; may cause warfarin failure',
      mechanism: 'CYP3A4 induction increases warfarin metabolism, reducing anticoagulant effect',
      management: 'Avoid combination',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },

    // ════════════════════════════════════════════════════════════════════
    // CRITICAL (life-threatening — pharmacist must intervene)
    // ════════════════════════════════════════════════════════════════════
    {
      drug1: 'warfarin', drug2: 'aspirin',
      severity: 'critical', category: 'drug-drug',
      description: 'Markedly increased risk of major bleeding, including GI bleeding',
      mechanism: 'Additive anticoagulant + antiplatelet effects; aspirin also displaces warfarin from protein binding',
      management: 'Avoid combination unless specifically prescribed by cardiologist. If unavoidable, monitor INR closely and use lowest effective aspirin dose',
      onset: 'delayed', evidence: 'established', source: 'BNF, ACC/AHA',
    },
    {
      drug1: 'warfarin', drug2: 'ibuprofen',
      severity: 'critical', category: 'drug-drug',
      description: 'Increased risk of GI bleeding; NSAID reduces warfarin protein binding',
      mechanism: 'NSAID inhibition of COX-1 reduces prostaglandin gastric mucosal protection; also displaces warfarin from albumin',
      management: 'Avoid all NSAIDs in patients on warfarin. Use paracetamol for pain (limit to standard doses)',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'warfarin', drug2: 'diclofenac',
      severity: 'critical', category: 'drug-drug',
      description: 'Increased risk of GI bleeding',
      mechanism: 'NSAID antiplatelet effect + warfarin anticoagulation; gastric mucosal damage',
      management: 'Avoid combination. Use paracetamol for pain',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'warfarin', drug2: 'naproxen',
      severity: 'critical', category: 'drug-drug',
      description: 'High risk of serious GI bleeding',
      mechanism: 'Additive anticoagulant + antiplatelet effects; naproxen is a particularly potent COX-1 inhibitor',
      management: 'Avoid combination entirely',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'ciprofloxacin', drug2: 'theophylline',
      severity: 'critical', category: 'drug-drug',
      description: 'Ciprofloxacin inhibits theophylline metabolism, risk of theophylline toxicity',
      mechanism: 'CYP1A2 inhibition reduces theophylline clearance, leading to toxic serum levels',
      management: 'Monitor theophylline levels closely; reduce dose by 30-50%. Consider alternative antibiotic (azithromycin)',
      onset: 'delayed', evidence: 'established', source: 'BNF, Lexicomp',
    },
    {
      drug1: 'potassium chloride', drug2: 'spironolactone',
      severity: 'critical', category: 'drug-drug',
      description: 'Risk of severe hyperkalaemia, potentially fatal cardiac arrhythmias',
      mechanism: 'Both drugs retain potassium — spironolactone is a potassium-sparing diuretic',
      management: 'Avoid potassium supplements with spironolactone. Monitor serum potassium and ECG',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'enalapril', drug2: 'potassium',
      severity: 'critical', category: 'drug-drug',
      description: 'ACE inhibitors reduce aldosterone, causing potassium retention with supplements',
      mechanism: 'ACE inhibition reduces angiotensin II and aldosterone, decreasing renal potassium excretion',
      management: 'Avoid potassium supplements with ACE inhibitors. Monitor potassium levels',
      onset: 'delayed', evidence: 'established', source: 'BNF, NICE',
    },
    {
      drug1: 'lisinopril', drug2: 'potassium',
      severity: 'critical', category: 'drug-drug',
      description: 'Risk of severe hyperkalaia with ACE inhibitors and potassium supplements',
      mechanism: 'ACE inhibition reduces aldosterone secretion, impairing potassium excretion',
      management: 'Monitor potassium levels. Avoid potassium supplements unless specifically prescribed',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'losartan', drug2: 'potassium',
      severity: 'critical', category: 'drug-drug',
      description: 'ARBs reduce aldosterone, increasing risk of hyperkalaemia with potassium supplements',
      mechanism: 'Angiotensin receptor blockade reduces aldosterone, decreasing renal potassium excretion',
      management: 'Monitor potassium levels. Avoid potassium supplements',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'digoxin', drug2: 'verapamil',
      severity: 'critical', category: 'drug-drug',
      description: 'Verapamil increases digoxin serum levels; risk of digoxin toxicity',
      mechanism: 'Verapamil inhibits P-glycoprotein-mediated digoxin efflux, increasing bioavailability',
      management: 'Reduce digoxin dose by 50% when starting verapamil. Monitor digoxin levels',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'digoxin', drug2: 'amiodarone',
      severity: 'critical', category: 'drug-drug',
      description: 'Amiodarone significantly increases digoxin levels — risk of fatal arrhythmias',
      mechanism: 'Amiodarone inhibits P-gp and reduces digoxin renal and non-renal clearance',
      management: 'Reduce digoxin dose by 50%. Monitor serum digoxin levels and ECG',
      onset: 'delayed', evidence: 'established', source: 'BNF, ESC',
    },
    {
      drug1: 'fluoxetine', drug2: 'tramadol',
      severity: 'critical', category: 'drug-drug',
      description: 'Increased risk of serotonin syndrome and seizures',
      mechanism: 'Both drugs increase serotonergic and noradrenergic neurotransmission',
      management: 'Use alternative analgesic. If unavoidable, monitor closely for serotonin syndrome symptoms',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'fluoxetine', drug2: 'tramadol',
      severity: 'critical', category: 'drug-drug',
      description: 'Serotonin syndrome risk — agitation, hyperthermia, rigidity, autonomic instability',
      mechanism: 'Combined serotonergic effect from SSRI + tramadol (SNRI activity)',
      management: 'Avoid combination. Use non-serotonergic analgesics',
      onset: 'delayed', evidence: 'probable', source: 'BNF, MHRA',
    },
    {
      drug1: 'carbamazepine', drug2: 'erythromycin',
      severity: 'critical', category: 'drug-drug',
      description: 'Erythromycin inhibits carbamazepine metabolism; risk of carbamazepine toxicity',
      mechanism: 'Erythromycin is a potent CYP3A4 inhibitor; carbamazepine is a CYP3A4 substrate',
      management: 'Monitor carbamazepine levels; use azithromycin as alternative (no CYP3A4 interaction)',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'carbamazepine', drug2: 'clarithromycin',
      severity: 'critical', category: 'drug-drug',
      description: 'Clarithromycin strongly inhibits carbamazepine metabolism',
      mechanism: 'CYP3A4 inhibition increases carbamazepine serum concentrations to toxic levels',
      management: 'Use azithromycin instead. If clarithromycin unavoidable, monitor carbamazepine levels',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'sildenafil', drug2: 'glyceryl trinitrate',
      severity: 'critical', category: 'drug-drug',
      description: 'Risk of severe, potentially fatal hypotension',
      mechanism: 'Both drugs cause nitric-oxide-mediated vasodilation; combined effect is synergistic',
      management: 'Do not give nitrates within 24h of sildenafil (or 48h of tadalafil)',
      onset: 'immediate', evidence: 'established', source: 'BNF, FDA',
    },
    {
      drug1: 'sildenafil', drug2: 'isosorbide dinitrate',
      severity: 'critical', category: 'drug-drug',
      description: 'Risk of severe hypotension and cardiovascular collapse',
      mechanism: 'Additive nitric-oxide-mediated smooth muscle relaxation and vasodilation',
      management: 'Contraindicated. Ensure at least 24h gap between sildenafil and nitrates',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },

    // ════════════════════════════════════════════════════════════════════
    // SEVERE (significant clinical risk — close monitoring required)
    // ════════════════════════════════════════════════════════════════════
    {
      drug1: 'amlodipine', drug2: 'simvastatin',
      severity: 'severe', category: 'drug-drug',
      description: 'Amlodipine increases simvastatin exposure; risk of myopathy and rhabdomyolysis',
      mechanism: 'Amlodipine inhibits CYP3A4-mediated simvastatin metabolism',
      management: 'Limit simvastatin to 20mg/day when used with amlodipine. Consider alternative statin',
      onset: 'delayed', evidence: 'established', source: 'MHRA, FDA',
    },
    {
      drug1: 'atorvastatin', drug2: 'clarithromycin',
      severity: 'severe', category: 'drug-drug',
      description: 'Clarithromycin inhibits atorvastatin metabolism; risk of rhabdomyolysis',
      mechanism: 'CYP3A4 inhibition markedly increases atorvastatin serum concentrations',
      management: 'Hold atorvastatin during clarithromycin course. Use azithromycin as alternative antibiotic',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'simvastatin', drug2: 'clarithromycin',
      severity: 'severe', category: 'drug-drug',
      description: 'Markedly increased risk of myopathy and rhabdomyolysis',
      mechanism: 'Strong CYP3A4 inhibition increases simvastatin acid levels',
      management: 'Stop simvastatin during clarithromycin therapy. Resume 7 days after completion',
      onset: 'delayed', evidence: 'established', source: 'MHRA',
    },
    {
      drug1: 'atorvastatin', drug2: 'itraconazole',
      severity: 'severe', category: 'drug-drug',
      description: 'Itraconazole increases statin levels; risk of rhabdomyolysis',
      mechanism: 'Potent CYP3A4 inhibition',
      management: 'Use fluconazole (lower CYP3A4 inhibition) or reduce atorvastatin dose. Monitor CK',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'ciprofloxacin', drug2: 'aluminum hydroxide',
      severity: 'severe', category: 'drug-drug',
      description: 'Antacids containing aluminium/magnesium reduce ciprofloxacin absorption by 90%',
      mechanism: 'Cationic antacids chelate fluoroquinolones in the GI tract, preventing absorption',
      management: 'Separate doses by at least 2 hours. Give ciprofloxacin first',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'ciprofloxacin', drug2: 'magnesium hydroxide',
      severity: 'severe', category: 'drug-drug',
      description: 'Antacids reduce ciprofloxacin absorption',
      mechanism: 'Divalent/trivalent cations chelate fluoroquinolones',
      management: 'Separate doses by at least 2 hours',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'iron', drug2: 'ciprofloxacin',
      severity: 'severe', category: 'drug-drug',
      description: 'Iron supplements reduce ciprofloxacin absorption significantly',
      mechanism: 'Iron cations chelate the fluoroquinolone molecule in the GI tract',
      management: 'Separate iron and ciprofloxacin doses by at least 2 hours',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'calcium', drug2: 'ciprofloxacin',
      severity: 'severe', category: 'drug-drug',
      description: 'Calcium reduces fluoroquinolone absorption',
      mechanism: 'Calcium ions chelate ciprofloxacin in the GI tract',
      management: 'Separate doses by at least 2 hours',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'warfarin', drug2: 'fluconazole',
      severity: 'severe', category: 'drug-drug',
      description: 'Fluconazole increases INR significantly — bleeding risk',
      mechanism: 'CYP2C9 inhibition reduces warfarin metabolism',
      management: 'Monitor INR closely. Reduce warfarin dose by 30-50% when starting fluconazole',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'warfarin', drug2: 'metronidazole',
      severity: 'severe', category: 'drug-drug',
      description: 'Metronidazole increases INR and bleeding risk',
      mechanism: 'Inhibition of warfarin-metabolizing CYP enzymes',
      management: 'Monitor INR 3-5 days after starting metronidazole. Reduce warfarin dose if INR exceeds target',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'phenytoin', drug2: 'carbamazepine',
      severity: 'severe', category: 'drug-drug',
      description: 'Complex interaction — levels of both drugs may change unpredictably',
      mechanism: 'Carbamazepine induces phenytoin metabolism but also competes for protein binding; phenytoin inhibits carbamazepine epoxide metabolism',
      management: 'Monitor levels of both drugs. Avoid combination when possible',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'phenytoin', drug2: 'warfarin',
      severity: 'severe', category: 'drug-drug',
      description: 'Unpredictable interaction on warfarin effect',
      mechanism: 'Phenytoin is a CYP inducer (decreases warfarin) but also displaces it from protein binding (increases free warfarin)',
      management: 'Monitor INR very closely. Effect may change over time as enzyme induction develops',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'rifampicin', drug2: 'warfarin',
      severity: 'severe', category: 'drug-drug',
      description: 'Rifampicin markedly reduces warfarin effect through enzyme induction',
      mechanism: 'Potent CYP450 and P-gp induction increases warfarin clearance',
      management: 'Monitor INR frequently. Warfarin dose may need to be doubled or tripled. Re-adjust when rifampicin stopped',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'rifampicin', drug2: 'oral contraceptive',
      severity: 'severe', category: 'drug-drug',
      description: 'Rifampicin reduces effectiveness of combined oral contraceptives',
      mechanism: 'CYP3A4 induction increases metabolism of oestrogen and progestogen',
      management: 'Advise additional non-hormonal contraception during and for 4-8 weeks after rifampicin',
      onset: 'delayed', evidence: 'established', source: 'BNF, WHO',
    },
    {
      drug1: 'spironolactone', drug2: 'enalapril',
      severity: 'severe', category: 'drug-drug',
      description: 'Dual RAAS blockade increases risk of hyperkalaemia and renal impairment',
      mechanism: 'Both drugs reduce aldosterone effects on potassium excretion',
      management: 'Monitor potassium and renal function closely. Avoid in patients with CKD',
      onset: 'delayed', evidence: 'established', source: 'NICE, BNF',
    },
    {
      drug1: 'spironolactone', drug2: 'lisinopril',
      severity: 'severe', category: 'drug-drug',
      description: 'Combined RAAS blockade increases risk of hyperkalaemia',
      mechanism: 'Additive reduction in aldosterone-mediated potassium excretion',
      management: 'Monitor potassium and creatinine within 1-2 weeks of starting combination',
      onset: 'delayed', evidence: 'established', source: 'NICE',
    },
    {
      drug1: 'lithium', drug2: 'ibuprofen',
      severity: 'severe', category: 'drug-drug',
      description: 'NSAIDs increase lithium levels, risk of lithium toxicity',
      mechanism: 'NSAIDs reduce renal lithium clearance through prostaglandin inhibition',
      management: 'Avoid NSAIDs. If essential, monitor lithium levels closely and maintain hydration',
      onset: 'delayed', evidence: 'established', source: 'BNF, NICE',
    },
    {
      drug1: 'lithium', drug2: 'diclofenac',
      severity: 'severe', category: 'drug-drug',
      description: 'Diclofenac increases lithium serum levels',
      mechanism: 'Reduced renal lithium clearance via prostaglandin inhibition',
      management: 'Avoid if possible. Monitor lithium levels 3-5 days after starting',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'lithium', drug2: 'hydrochlorothiazide',
      severity: 'severe', category: 'drug-drug',
      description: 'Thiazides increase lithium reabsorption — risk of lithium toxicity',
      mechanism: 'Sodium depletion from diuresis increases proximal tubular lithium reabsorption',
      management: 'Avoid if possible. If essential, monitor lithium levels frequently and reduce dose',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'lithium', drug2: 'furosemide',
      severity: 'severe', category: 'drug-drug',
      description: 'Loop diuretics can increase lithium levels',
      mechanism: 'Initial sodium loss increases lithium reabsorption; high-dose loop diuretics may increase clearance',
      management: 'Monitor lithium levels. Ensure adequate hydration',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'antacid', drug2: 'itraconazole',
      severity: 'severe', category: 'drug-drug',
      description: 'Antacids reduce itraconazole absorption',
      mechanism: 'Reduced gastric acidity impairs dissolution and absorption of itraconazole',
      management: 'Separate doses by at least 2 hours. Give itraconazole with acidic beverage (cola)',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'antacid', drug2: 'ketoconazole',
      severity: 'severe', category: 'drug-drug',
      description: 'Antacids reduce ketoconazole absorption',
      mechanism: 'Ketoconazole requires acidic environment for dissolution',
      management: 'Separate by at least 2 hours',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'oral contraceptive', drug2: 'amoxicillin',
      severity: 'severe', category: 'drug-drug',
      description: 'Broad-spectrum antibiotics may reduce oral contraceptive effectiveness',
      mechanism: 'Antibiotics alter gut flora, reducing enterohepatic recirculation of oestrogen',
      management: 'Advise additional contraception during antibiotic course and for 7 days after',
      onset: 'delayed', evidence: 'probable', source: 'BNF, FSRH',
    },
    {
      drug1: 'oral contraceptive', drug2: 'doxycycline',
      severity: 'severe', category: 'drug-drug',
      description: 'Doxycycline may reduce oral contraceptive effectiveness',
      mechanism: 'Altered gut flora reduces oestrogen reabsorption',
      management: 'Use additional contraception during and for 7 days after doxycycline',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },

    // ════════════════════════════════════════════════════════════════════
    // MODERATE (monitor — may require dose adjustment)
    // ════════════════════════════════════════════════════════════════════
    {
      drug1: 'paracetamol', drug2: 'warfarin',
      severity: 'moderate', category: 'drug-drug',
      description: 'High-dose or prolonged paracetamol may increase INR',
      mechanism: 'Paracetamol or its metabolites may interfere with vitamin K cycle at high doses',
      management: 'Limit to standard doses (max 4g/day). Monitor INR if prolonged use (>1 week)',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'ibuprofen', drug2: 'lisinopril',
      severity: 'moderate', category: 'drug-drug',
      description: 'NSAIDs reduce antihypertensive effect and risk of renal impairment',
      mechanism: 'NSAID inhibition of prostaglandins reduces renal blood flow and blunts ACE inhibitor effect',
      management: 'Short-term use only. Monitor BP and renal function',
      onset: 'delayed', evidence: 'established', source: 'NICE, BNF',
    },
    {
      drug1: 'ibuprofen', drug2: 'enalapril',
      severity: 'moderate', category: 'drug-drug',
      description: 'NSAIDs may reduce antihypertensive effect; risk of acute renal failure',
      mechanism: 'Prostaglandin synthesis inhibition reduces renal perfusion, counteracting ACE inhibitor',
      management: 'Use shortest duration and lowest dose. Monitor BP, U&E',
      onset: 'delayed', evidence: 'established', source: 'NICE',
    },
    {
      drug1: 'ibuprofen', drug2: 'losartan',
      severity: 'moderate', category: 'drug-drug',
      description: 'NSAIDs reduce ARB antihypertensive effect; risk of renal impairment',
      mechanism: 'Prostaglandin inhibition reduces renal blood flow',
      management: 'Short-term use only. Monitor renal function',
      onset: 'delayed', evidence: 'established', source: 'NICE',
    },
    {
      drug1: 'aspirin', drug2: 'ibuprofen',
      severity: 'moderate', category: 'drug-drug',
      description: 'Ibuprofen may interfere with aspirin antiplatelet effect',
      mechanism: 'Ibuprofen competitively blocks aspirin binding to COX-1, preventing irreversible platelet inhibition',
      management: 'Take ibuprofen at least 30 minutes after or 8 hours before aspirin. Consider paracetamol instead',
      onset: 'immediate', evidence: 'established', source: 'FDA, MHRA',
    },
    {
      drug1: 'amoxicillin', drug2: 'allopurinol',
      severity: 'moderate', category: 'drug-drug',
      description: 'Increased risk of rash (ampicillin/allopurinol rash)',
      mechanism: 'Mechanism unclear — may be immune-mediated',
      management: 'Monitor for skin reactions. Not a contraindication but be aware',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'hydrochlorothiazide', drug2: 'diclofenac',
      severity: 'moderate', category: 'drug-drug',
      description: 'NSAIDs may reduce diuretic effect; risk of renal impairment',
      mechanism: 'Prostaglandin inhibition reduces GFR, counteracting diuretic effect',
      management: 'Monitor renal function with combined use. Ensure adequate hydration',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'metformin', drug2: 'enalapril',
      severity: 'moderate', category: 'drug-drug',
      description: 'Combined use may increase risk of lactic acidosis in renal impairment',
      mechanism: 'Both drugs can affect renal function additively',
      management: 'Monitor renal function. Avoid if eGFR < 30',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'ciprofloxacin', drug2: 'dexamethasone',
      severity: 'moderate', category: 'drug-drug',
      description: 'Fluoroquinolones + corticosteroids increase risk of tendon damage',
      mechanism: 'Both drugs independently increase risk of tendinitis and tendon rupture',
      management: 'Advise patient to report any tendon pain. Avoid in elderly or those on steroids',
      onset: 'delayed', evidence: 'probable', source: 'MHRA, FDA',
    },
    {
      drug1: 'ciprofloxacin', drug2: 'prednisolone',
      severity: 'moderate', category: 'drug-drug',
      description: 'Increased risk of Achilles tendon rupture',
      mechanism: 'Additive effect on collagen degradation and tendon weakening',
      management: 'Monitor for tendon pain. Stop fluoroquinolone if symptoms develop',
      onset: 'delayed', evidence: 'probable', source: 'MHRA',
    },
    {
      drug1: 'omeprazole', drug2: 'diazepam',
      severity: 'moderate', category: 'drug-drug',
      description: 'Omeprazole may increase diazepam levels',
      mechanism: 'CYP2C19 inhibition reduces diazepam metabolism',
      management: 'Monitor for increased sedation. Consider dose reduction of diazepam',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'omeprazole', drug2: 'phenytoin',
      severity: 'moderate', category: 'drug-drug',
      description: 'Omeprazole may increase phenytoin levels',
      mechanism: 'CYP2C19 inhibition reduces phenytoin metabolism',
      management: 'Monitor phenytoin levels when starting or stopping omeprazole',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'carbamazepine', drug2: 'oral contraceptive',
      severity: 'moderate', category: 'drug-drug',
      description: 'Carbamazepine reduces oral contraceptive effectiveness',
      mechanism: 'CYP3A4 induction increases metabolism of oestrogen and progestogen',
      management: 'Advise additional or alternative contraception. Consider higher-dose pill',
      onset: 'delayed', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'phenytoin', drug2: 'oral contraceptive',
      severity: 'moderate', category: 'drug-drug',
      description: 'Phenytoin may reduce oral contraceptive effectiveness',
      mechanism: 'CYP3A4 induction',
      management: 'Advise additional barrier contraception',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'isoniazid', drug2: 'carbamazepine',
      severity: 'moderate', category: 'drug-drug',
      description: 'Isoniazid inhibits carbamazepine metabolism, increasing toxicity risk',
      mechanism: 'CYP3A4 and CYP2C9 inhibition',
      management: 'Monitor carbamazepine levels. Reduce dose if needed',
      onset: 'delayed', evidence: 'probable', source: 'BNF, WHO',
    },
    {
      drug1: 'isoniazid', drug2: 'warfarin',
      severity: 'moderate', category: 'drug-drug',
      description: 'Isoniazid may increase INR',
      mechanism: 'CYP inhibition reduces warfarin metabolism',
      management: 'Monitor INR weekly for first 2 weeks of isoniazid therapy',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },

    // ════════════════════════════════════════════════════════════════════
    // MILD (minor — usually no action needed but be aware)
    // ════════════════════════════════════════════════════════════════════
    {
      drug1: 'paracetamol', drug2: 'ibuprofen',
      severity: 'mild', category: 'drug-drug',
      description: 'No clinically significant interaction. Safe to use together',
      mechanism: 'Different mechanisms of action; no pharmacokinetic interaction',
      management: 'No action needed. Combination can provide better analgesia',
      onset: 'none', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'paracetamol', drug2: 'amoxicillin',
      severity: 'mild', category: 'drug-drug',
      description: 'No significant interaction',
      mechanism: 'No known pharmacokinetic or pharmacodynamic interaction',
      management: 'No action needed',
      onset: 'none', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'cetirizine', drug2: 'erythromycin',
      severity: 'mild', category: 'drug-drug',
      description: 'Minor pharmacokinetic interaction — no clinical significance',
      mechanism: 'Erythromycin causes small increase in cetirizine levels',
      management: 'No dose adjustment needed',
      onset: 'none', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'omeprazole', drug2: 'amoxicillin',
      severity: 'mild', category: 'drug-drug',
      description: 'No clinically significant interaction',
      mechanism: 'Both used together in H. pylori eradication regimens',
      management: 'No action needed',
      onset: 'none', evidence: 'established', source: 'BNF',
    },
    {
      drug1: 'alcohol', drug2: 'paracetamol',
      severity: 'mild', category: 'drug-food',
      description: 'Chronic alcohol use increases risk of paracetamol hepatotoxicity',
      mechanism: 'Alcohol induces CYP2E1, increasing formation of toxic paracetamol metabolite (NAPQI)',
      management: 'Caution with chronic alcohol users. Avoid high-dose paracetamol (>2g/day) in heavy drinkers',
      onset: 'delayed', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'alcohol', drug2: 'warfarin',
      severity: 'mild', category: 'drug-food',
      description: 'Acute alcohol intoxication may increase INR; chronic heavy use may decrease it',
      mechanism: 'Complex: acute alcohol competes for CYP metabolism; chronic use induces CYP enzymes',
      management: 'Advise moderation. Binge drinking is most dangerous',
      onset: 'variable', evidence: 'probable', source: 'BNF',
    },
    {
      drug1: 'food (high-fat)', drug2: 'albendazole',
      severity: 'mild', category: 'drug-food',
      description: 'High-fat food significantly increases albendazole absorption',
      mechanism: 'Enhanced solubility of lipophilic drug in fatty meal',
      management: 'Give albendazole with food to improve absorption',
      onset: 'immediate', evidence: 'established', source: 'WHO Model Formulary',
    },
    {
      drug1: 'food (calcium-rich)', drug2: 'ciprofloxacin',
      severity: 'mild', category: 'drug-food',
      description: 'Dairy products (milk, yoghurt) may slightly reduce ciprofloxacin absorption',
      mechanism: 'Calcium cations partially chelate the fluoroquinolone',
      management: 'Separate ciprofloxacin from dairy by 1-2 hours if possible',
      onset: 'immediate', evidence: 'established', source: 'BNF',
    },
  ]
}
